CREATE TABLE place (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(15) NOT NULL,
    warehouse_id BIGINT,
    CONSTRAINT place_name_warehouse_id_unique UNIQUE(name, warehouse_id),
    CONSTRAINT fk_place_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse(id)
);
