CREATE TABLE company (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    short_name VARCHAR(4) UNIQUE NOT NULL,
    name VARCHAR(25) NOT NULL,
    address_id BIGINT,
    CONSTRAINT fk_company_address FOREIGN KEY (address_id) REFERENCES address(id)
);