CREATE TABLE stock (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    article_id BIGINT,
    CONSTRAINT fk_stock_article FOREIGN KEY (article_id) REFERENCES article(id),
    place_id BIGINT,
    CONSTRAINT fk_stock_place FOREIGN KEY (place_id) REFERENCES place(id)
);